### ISSUE TITLE
国内安装PyTorch出现CondaHTTPError

### ISSUE THREAD

**Issue by dragen1860** [dragen1860/Deep-Learning-with-PyTorch-Tutorials#1]

**Comment by dragen1860** [comment]
这是因为PyTorch的服务器在国外，国内下载650M文件经常连接不稳定。
解决方法：

方法1. 科学上网（尤其适合国内，以后还会用很多地方需要科学上网，步骤较多，一劳永逸！）：shadowsocks
可参考教程：https://github.com/Shadowsocks-Wiki/shadowsocks/blob/master/2-windows-setup-guide-cn.md

方法2. 更改conda为国内源：
```
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
conda config --set show_channel_urls yes
```
注意是一句一句地执行，并且这个配置过程没有结果输出的（不要以为自己错了）。
接着继续使用pytorch的安装命令进行。
![image](https://user-images.githubusercontent.com/4252555/51794090-6415ed80-221f-11e9-8fc4-a165497b675f.png)
注意上图的URL已经指向清华大学了，成功！

3. 源码安装、pip安装
步骤较多，不推荐新手。

**Comment by lighTQ** [comment]
现在好像都不行了，参考这个暂时装好了 
https://blog.csdn.net/qq_27882063/article/details/91128270
