### ISSUE TITLE
In lesson53, Torchtext.data.Field has been deprecated in the latest version.

### ISSUE THREAD

**Issue by flowerfalling** [dragen1860/Deep-Learning-with-PyTorch-Tutorials#13]
## So how to use data in the latest version of torchtext?

In version 0.9, Torchtext.data.Field was moved to torchtext.legacy.data.Field.[here](https://github.com/pytorch/text/releases/tag/v0.9.0-rc5)

In version 0.12, they had removed the legacy folder in this release.[here](https://github.com/pytorch/text/issues/1422)

**Comment by flowerfalling** [comment]
Maybe this is not a very big problem. I think I can try to solve it. Thank you.

**Comment by Bhavya-2k03** [comment]
How to solve this? I have been trying for quite some time but couldn't figure it out.

**Comment by Bhavya-2k03** [comment]
How to solve this? I have been trying for quite some time but couldn't figure it out.
