### ISSUE TITLE
Lesson30 Visdom 可视化程序内没有visdom相应内容

### ISSUE THREAD

**Issue by kevinlemon** [dragen1860/Deep-Learning-with-PyTorch-Tutorials#2]
老师您好，Lesson30 Visdom 可视化程序内没有visdom相应内容，只是MLP对MNIST的分类程序

**Comment by dragen1860** [comment]
@kevinlemon 你好，lesson30和lesson29的代码搞反了，visdom在lesson29里面，谢谢。
